Ext.define('BasketballDashboard.model.GameEventModel', {
    extend: 'Ext.data.Model',
    fields: [
        {name:'id', type: 'int'},
        {name: 'name', type: 'string'},
        {name: 'a1', type: 'string'},
        {name: 'a2', type: 'string'},
        {name: 'a3', type: 'string'},
        {name: 'a4', type: 'string'},
        {name: 'a5', type: 'string'},
        {name: 'h1', type: 'string'},
        {name: 'h2', type: 'string'},
        {name: 'h3', type: 'string'},
        {name: 'h4', type: 'string'},
        {name: 'h5', type: 'string'},
        {name: 'period', type: 'int'},
        {name: 'time', type: 'string'},
        {name: 'team', type: 'string'},
        {name: 'etype', type: 'string'},
        {name: 'assist', type: 'string'},
        {name: 'away', type: 'string'},
        {name: 'block', type: 'string'},
        {name: 'entered', type: 'string'},
        {name: 'home', type: 'string'},
        {name: 'left', type: 'string'},
        {name: 'num', type: 'string'},
        {name: 'opponent', type: 'string'},
        {name: 'outof', type: 'string'},
        {name: 'player', type: 'string'},
        {name: 'points', type: 'int'},
        {name: 'possession', type: 'string'},
        {name: 'reason', type: 'string'},
        {name: 'result', type: 'string'},
        {name: 'steal', type: 'string'},
        {name: 'type', type: 'string'},
        {name: 'x', type: 'int'},
        {name: 'y', type: 'int'}
    ]
});