// Generated by CoffeeScript 1.6.1
/*
Ext.ux.d3.Visualization - Ext JS component wrapper for d3.js visualizations
http://github.com/CodeCatalyst/Ext.ux.d3.Visualization

@author John Yanarella
@version: 1.0.0

Copyright (c) 2013 CodeCatalyst, LLC - http://www.codecatalyst.com/

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

Ext.define('BasketballDashboard.Visualization', {
  extend: 'Ext.Component',
  alias: 'widget.d3',
  mixins: {
    bindable: 'Ext.util.Bindable'
  },
  /**
  	@protected
  	The d3 visualization instance wrapped by this component.
  */

  visualization: null,
  /**
  	@inheritdoc
  */

  initComponent: function() {
    this.on({
      resize: {
        fn: this.onResize,
        scope: this
      }
    });
    return this.callParent(arguments);
  },
  /**
  	Re-render the visualization.
  */

  refresh: function() {
    d3.select(this.el.dom).datum(this.getData()).call(this.visualization);
  },
  /**
  	@inheritdoc
  */

  afterRender: function() {
    this.refresh();
    return this.callParent(arguments);
  },
  /**
  	@protected
  	Updates the wrapped visualization when this component is resized.
  */

  onResize: function() {
    this.visualization.width(this.getWidth()).height(this.getHeight());
    if (this.visualization.refresh != null) {
      this.visualization.refresh();
    } else {
      this.refresh();
    }
  },
  /**
  	@inheritdoc
  */

  bindStore: function(store, initial) {
    this.mixins.bindable.bindStore.apply(this, arguments);
    if (this.rendered && this.store && !initial) {
      this.refresh();
    }
  },
  /**
  	@inheritdoc
  */

  getStoreListeners: function() {
    var buffer,
        listeners;

    buffer = 0;

    listeners = {
      refresh: {
        fn: this.refresh,
        scope: this
      },
      add: {
        fn: this.refresh,
        scope: this,
        buffer: buffer
      },
      bulkremove: {
        fn: this.refresh,
        scope: this,
        buffer: buffer
      },
      update: {
        fn: this.refresh,
        scope: this,
        buffer: buffer
      },
      clear: {
        fn: this.refresh,
        scope: this
      }
    };
    return listeners;
  },
  /**
  	@protected
  	@method
  	Returns the data to apply to the visualization. The stock implementation
  	generates an appropriate Array representation of this component's store.
  */
  getData: function(store) {
    var data;
    data = [];
    if (this.store != null) {
      this.store.each(function(model) {
        return data.push(model.getData());
      });
    }
    return data;
  }
});
